# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from lwh_isaaclab_tasks.policy.transport import services_pb2 as lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2


class LearnerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamParameters = channel.unary_stream(
                '/transport.LearnerService/StreamParameters',
                request_serializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.SerializeToString,
                response_deserializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Parameters.FromString,
                )
        self.SendTransitions = channel.stream_unary(
                '/transport.LearnerService/SendTransitions',
                request_serializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Transition.SerializeToString,
                response_deserializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.FromString,
                )
        self.SendInteractions = channel.stream_unary(
                '/transport.LearnerService/SendInteractions',
                request_serializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.InteractionMessage.SerializeToString,
                response_deserializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.FromString,
                )
        self.Ready = channel.unary_unary(
                '/transport.LearnerService/Ready',
                request_serializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.SerializeToString,
                response_deserializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.FromString,
                )


class LearnerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTransitions(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendInteractions(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ready(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LearnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamParameters': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamParameters,
                    request_deserializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.FromString,
                    response_serializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Parameters.SerializeToString,
            ),
            'SendTransitions': grpc.stream_unary_rpc_method_handler(
                    servicer.SendTransitions,
                    request_deserializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Transition.FromString,
                    response_serializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.SerializeToString,
            ),
            'SendInteractions': grpc.stream_unary_rpc_method_handler(
                    servicer.SendInteractions,
                    request_deserializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.InteractionMessage.FromString,
                    response_serializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.SerializeToString,
            ),
            'Ready': grpc.unary_unary_rpc_method_handler(
                    servicer.Ready,
                    request_deserializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.FromString,
                    response_serializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transport.LearnerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LearnerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/transport.LearnerService/StreamParameters',
            lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.SerializeToString,
            lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Parameters.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendTransitions(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/transport.LearnerService/SendTransitions',
            lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Transition.SerializeToString,
            lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendInteractions(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/transport.LearnerService/SendInteractions',
            lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.InteractionMessage.SerializeToString,
            lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ready(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transport.LearnerService/Ready',
            lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.SerializeToString,
            lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class AsyncInferenceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendObservations = channel.stream_unary(
                '/transport.AsyncInference/SendObservations',
                request_serializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Observation.SerializeToString,
                response_deserializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.FromString,
                )
        self.GetActions = channel.unary_unary(
                '/transport.AsyncInference/GetActions',
                request_serializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.SerializeToString,
                response_deserializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Actions.FromString,
                )
        self.SendPolicyInstructions = channel.unary_unary(
                '/transport.AsyncInference/SendPolicyInstructions',
                request_serializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.PolicySetup.SerializeToString,
                response_deserializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.FromString,
                )
        self.Ready = channel.unary_unary(
                '/transport.AsyncInference/Ready',
                request_serializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.SerializeToString,
                response_deserializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.FromString,
                )


class AsyncInferenceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendObservations(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPolicyInstructions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ready(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AsyncInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendObservations': grpc.stream_unary_rpc_method_handler(
                    servicer.SendObservations,
                    request_deserializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Observation.FromString,
                    response_serializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.SerializeToString,
            ),
            'GetActions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActions,
                    request_deserializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.FromString,
                    response_serializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Actions.SerializeToString,
            ),
            'SendPolicyInstructions': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPolicyInstructions,
                    request_deserializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.PolicySetup.FromString,
                    response_serializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.SerializeToString,
            ),
            'Ready': grpc.unary_unary_rpc_method_handler(
                    servicer.Ready,
                    request_deserializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.FromString,
                    response_serializer=lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transport.AsyncInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AsyncInference(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendObservations(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/transport.AsyncInference/SendObservations',
            lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Observation.SerializeToString,
            lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetActions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transport.AsyncInference/GetActions',
            lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.SerializeToString,
            lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Actions.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendPolicyInstructions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transport.AsyncInference/SendPolicyInstructions',
            lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.PolicySetup.SerializeToString,
            lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ready(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transport.AsyncInference/Ready',
            lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.SerializeToString,
            lwh__isaaclab__tasks_dot_policy_dot_transport_dot_services__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
